version: "3"
services:
  database:
    image: "postgres:alpine"
    env_file:
      - database.env.local
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - 6543:5432
volumes:
  database-data:
